# Generated by Django 5.1.7 on 2025-03-23 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('dimensions', models.CharField(max_length=50, verbose_name='Габариты')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('warehouse_address', models.TextField(verbose_name='Адрес склада')),
                ('delivery_date', models.DateField(verbose_name='Дата доставки')),
                ('status', models.CharField(default='Pending', max_length=50, verbose_name='Статус')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Компания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Logistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100, verbose_name='Имя водителя')),
                ('vehicle_number', models.CharField(max_length=20, verbose_name='Номер автомобиля')),
                ('departure_time', models.DateTimeField(verbose_name='Время отправления')),
                ('estimated_arrival', models.DateTimeField(verbose_name='Ориентировочное прибытие')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='logistics.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Логистика',
                'verbose_name_plural': 'Логистика',
            },
        ),
    ]
