# Generated by Django 5.1.7 on 2025-04-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_product_photo_delete_logistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, default='products/1.png', null=True, upload_to='products/', verbose_name='Фото'),
        ),
    ]
